version: "3.6"

services:

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: --config=/etc/otelcol/config.yaml
    volumes:
      - ./collector.yaml:/etc/otelcol/config.yaml
    #  - ./key.pem:/etc/otelcol/pem/key.pem
    #  - ./cert.pem:/etc/otelcol/pem/cert.pem
    #  - ./ca.pem:/etc/otelcol/pem/ca.pem
    environment:
      - NEW_RELIC_OTLP_ENDPOINT
      - NEW_RELIC_API_KEY
      - CLUSTER_BOOTSTRAP_SERVER
      - CLUSTER_API_KEY
      - CLUSTER_API_SECRET
      - CLUSTER_ID
      - CONFLUENT_API_ID
      - CONFLUENT_API_SECRET
    # - CONNECTOR_ID
    # - SCHEMA_REGISTRY_ID

