version: "3"
networks:
  my-net:
    driver: bridge
services:
  otel-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "4317"
      - "9411"
    networks:
      - my-net

