version: "3"
networks:
  my-net:
    driver: bridge
services:
  adservice:
    image: otel/demo:1.10.0-adservice
    ports:
      - "8080:8080"
      - "4317"
    environment:
      - AD_SERVICE_PORT=8080
      - OTEL_SERVICE_NAME
      - OTEL_EXPORTER_OTLP_ENDPOINT=${NEW_RELIC_OTLP_ENDPOINT}
      - OTEL_EXPORTER_OTLP_HEADERS=api-key=${NEW_RELIC_API_KEY}
    networks:
      - my-net


  

