extensions:
  health_check: {}
receivers:
  otlp:
    protocols:
      grpc:
  zipkin:
    endpoint: 0.0.0.0:9411
exporters:
  debug:
    verbosity: detailed
  otlp:
    endpoint: https://otlp.nr-data.net:4317
    headers:
      api-key: <NEW_RELIC_API_KEY>
processors:
  batch:
  resource:
    attributes:
      - key: host.id
        from_attribute: host.name
        action: insert

  resourcedetection:
    detectors: ["env", "system"]

  resourcedetection/cloud:
    detectors: ["gcp", "ec2", "azure"]
    timeout: 2s
    override: false

  resourcedetection/system:
    detectors: [env, system, gcp, eks]
    timeout: 2s
    override: false

service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [otlp]
      processors:
        [
          resourcedetection,
          resourcedetection/cloud,
          resourcedetection/system,
          resource,
          batch,
        ]
      exporters: [debug, otlp]
    traces:
      receivers: [otlp, zipkin]
      processors:
        [
          resourcedetection,
          resourcedetection/cloud,
          resourcedetection/system,
          resource,
          batch,
        ]
      exporters: [debug, otlp]
    logs:
      receivers: [otlp]
      processors:
        [
          resourcedetection,
          resourcedetection/cloud,
          resourcedetection/system,
          resource,
          batch,
        ]
      exporters: [debug, otlp]
