services:
  collector:
    image: otel/opentelemetry-collector-contrib:0.146.0
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    volumes:
      - ./collector/collector.yaml:/etc/otelcol-contrib/config.yaml:ro
    environment:
      - NEW_RELIC_API_KEY=${NEW_RELIC_API_KEY}
      - NEW_RELIC_OTLP_ENDPOINT=${NEW_RELIC_OTLP_ENDPOINT:-https://otlp.nr-data.net}
    ports:
      - "24317:4317"
      - "24318:4318"
    networks:
      - faas-metrics-net

networks:
  faas-metrics-net:
    name: faas-metrics-net
