version: '3'
services:
  collector:
    image: otel/opentelemetry-collector-contrib:0.33.0
    volumes:
    - ./otel-config.yaml:/otel-config.yaml
    entrypoint: ["/otelcontribcol"]
    command: ["--config", "/otel-config.yaml"]
    environment:
      LOG_EXPORTER_LOG_LEVEL: "DEBUG"
      NEW_RELIC_API_KEY: "${NEW_RELIC_API_KEY}"
      OTEL_EXPORTER_OTLP_ENDPOINT: "${OTEL_EXPORTER_OTLP_ENDPOINT}"
    ports:
      - "4317:4317"     # grpc
      - "13133:13133"   # health
      - "8006:8006"     # fluentdforward
      - "8006:8006/udp" # fluentforward
