version: '3'
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.121.0
    volumes:
    - ./otel-config.yaml:/otel-config.yaml
    command: ["--config=/otel-config.yaml", "${OTELCOL_ARGS}"]
    environment:
      LOG_EXPORTER_LOG_VERBOSITY: "detailed"
      NEW_RELIC_API_KEY: "${NEW_RELIC_API_KEY}"
    ports:
      - "4317:4317"     # grpc
      - "4318:4318"     # http
      - "13133:13133"   # health
      - "8006:8006"     # fluentdforward
      - "8006:8006/udp" # fluentforward
