version: '3'
services:
  collector:
    container_name: docker-collector
    image: otel/opentelemetry-collector-contrib:0.98.0
    volumes:
    - ./config.yaml:/etc/otelcol-contrib/config.yaml
    - /var/run/docker.sock:/var/run/docker.sock
    # Set the user id used to run the collector. HOST_USER_ID is defined in .env, and MUST have permission to access the docker socket.
    user: ${HOST_USER_ID}
    # Expose the env vars defined in .env
    environment:
      - NEW_RELIC_API_KEY
      - NEW_RELIC_OTLP_ENDPOINT
      # host.id is required for New Relic.
      # Optionally manually set it if one of the resource detectors in config.yaml is unable to identify it.
      # - OTEL_RESOURCE_ATTRIBUTES=host.id=<INSERT_HOST_ID>

  adservice:
    container_name: docker-adservice
    image: otel/demo:1.10.0-adservice
    ports:
      - "8080:8080"
    environment:
      - AD_SERVICE_PORT=8080
      - OTEL_SERVICE_NAME=adservice
      - OTEL_EXPORTER_OTLP_ENDPOINT=${NEW_RELIC_OTLP_ENDPOINT}
      - OTEL_EXPORTER_OTLP_HEADERS=api-key=${NEW_RELIC_API_KEY}
