# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.2.2'

gem 'sinatra', '~> 3.0.6'
gem 'thin', '~> 1.8.2'

gem 'opentelemetry-sdk'
gem 'opentelemetry-metrics-sdk'
gem 'opentelemetry-exporter-otlp'
gem 'opentelemetry-exporter-otlp-metrics'
# gem 'opentelemetry-instrumentation-all'
gem 'opentelemetry-instrumentation-rack', github: 'kaylareopelle/opentelemetry-ruby-contrib', branch: 'metrics-alternative-prototype', glob: 'instrumentation/rack/*.gemspec'
