# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.4.5'

gem 'sinatra', '~> 4.2.1'
gem 'puma', '~> 8.0.2'

gem 'opentelemetry-sdk', '~> 1.13.0'
gem 'opentelemetry-exporter-otlp', '~> 0.34.1'
gem 'opentelemetry-instrumentation-all', '~> 0.96.0'